### PR TITLE
Fixes to pass cppcheck-1.90 warnings

### LINKED ISSUE #995: Multiple issues found with cppcheck
Hi! Here is an output from cppcheck showing a range of different issues (memory leaks, resource leaks, double free). The command run was `cppcheck  --enable=warning -q -f --language=c ./` on the root directory. Output:
```
(htslib) ( develop ) ><> cppcheck  --enable=warning -q -f --language=c ./                                                                                                          17:40:31
[htslib/kbitset.h:106]: (error) Common realloc mistake: 'bs' nulled but not freed upon failure
[cram/cram_codecs.c:2232]: (error) Memory leak: t
[cram/cram_decode.c:1148]: (error) Common realloc mistake: 'cigar' nulled but not freed upon failure
[cram/cram_encode.c:552]: (error) Memory leak: buf
[cram/cram_io.c:2830]: (error) Invalid calloc() argument nr 1. The value is 0 but the valid values are '1:'.
[cram/cram_io.c:2439]: (error) Memory leak: seq
[cram/cram_io.c:3788]: (error) Memory leak: header
[cram/cram_io.c:3840]: (error) Memory leak: header
[cram/cram_io.c:4079]: (error) Memory leak: pads
[cram/mFILE.c:351]: (error) Resource leak: fp
[cram/pooled_alloc.c:68]: (error) Memory leak: p
[cram/pooled_alloc.c:202]: (error) Memory leak: items
[cram/rANS_static.c:902]: (error) Resource leak: infp
[cram/rANS_static.c:902]: (error) Resource leak: outfp
[cram/string_alloc.c:59]: (error) Memory leak: a_str
[header.c:643]: (warning) When using 'char' variables in bit operations, sign extension can generate unexpected results.
[header.c:2406]: (warning) When using 'char' variables in bit operations, sign extension can generate unexpected results.
[htslib/sam.h:639] -> [header.c:1645]: (warning) Function 'sam_hdr_remove_lines' argument order different: declaration 'h, type, id, rh' definition 'bh, type, id, h'
[header.c:531]: (warning) When using 'char' variables in bit operations, sign extension can generate unexpected results.
[hfile_s3.c:922]: (error) Memory leak: queries
[hts.c:1435]: (error) Common realloc mistake: 's' nulled but not freed upon failure
[hts.c:1452]: (error) Common realloc mistake: 's' nulled but not freed upon failure
[hts.c:1457]: (error) Common realloc mistake: 's' nulled but not freed upon failure
[hts.c:1465]: (error) Common realloc mistake: 's' nulled but not freed upon failure
[hts.c:1473]: (error) Common realloc mistake: 's' nulled but not freed upon failure
[synced_bcf_reader.c:318]: (error) Uninitialized variable: n
[test/hfile.c:183]: (error) Memory leak: original
[test/hfile.c:183]: (error) Memory leak: text
[test/test_bgzf.c:381]: (warning) %d in format string (no. 1) requires 'int' but the argument type is 'unsigned int'.
[test/test_kstring.c:122]: (warning) %u in format string (no. 1) requires 'unsigned int' but the argument type is 'signed int'.
[thread_pool.c:644] -> [thread_pool.c:620]: (warning) Either the condition '!q' is redundant or there is possible null pointer dereference: q.
[thread_pool.c:644] -> [thread_pool.c:626]: (warning) Either the condition '!q' is redundant or there is possible null pointer dereference: q.
[thread_pool.c:644] -> [thread_pool.c:640]: (warning) Either the condition '!q' is redundant or there is possible null pointer dereference: q.
[thread_pool.c:63]: (error) va_list 'args' was opened but not closed by va_end().
[vcf.c:553]: (error) Memory pointed to by 'str' is freed twice.
```

### PR DESCRIPTION
**Pull request by jkbonfield**
Command ran: cppcheck --inline-suppr  --enable=warning -q -f --language=c .

This is a mix of silencing false positives, rewriting code to be less confusing to cppcheck (and sometimes to us), and genuine minor issues around handling running out of memory.

In some cases I've added inline suppressions, eg

    // cppcheck-suppress objectIndex

This isn't ideal, but I personally think it's worth having a little annotation in order to make detection of future buglets easier to find.

Fixes #995

Propose merging immediately *after* 1.10 release as there are no serious bugs fixed.

Note cppcheck 1.72 still finds some false positives, but I don't propose silencing them.  1.90 is the latest version at time of PR.

### CODE REVIEW

**Comment by jmarshall** [comment]
There's lots to be quibbled about with some of these fixes — e.g., it would be better to rewrite the reallocs in `hts_readlist()` and `hts_readlines()` via `hts_resize` instead.

So it will be good to come back and discuss this after the upcoming release.

**Comment by jkbonfield** [comment]
I'd forgotten about `hts_resize`.  In my mind it's still the abomination of zero error checking, but I'd conflated it with `hts_expand` that it replaced. :)

Agreed there are better solutions out there for some code and lots of it could be rewritten (especially in vcf.c), but IMO that's a second larger task than the naive quick fixes to get the code validation passing so personally I'd prefer separating the two out.

File: header.c [hunk 1]
```diff
@@ -528,7 +528,7 @@ static int sam_hrecs_vadd(sam_hrecs_t *hrecs, const char *type, va_list ap, ...)
     sam_hrec_type_t *h_type;
     sam_hrec_tag_t *h_tag, *last=NULL;
     int new;
-    khint32_t type_i = (type[0]<<8) | type[1], k;
+    khint32_t type_i = ((unsigned)type[0]<<8) | type[1], k;
```
Comment (jmarshall) [inline header.c]: This code appears eight times in _header.c_. Better to abstract it into `static inline unsigned int hdrtype2int(const char *type)` and fix seven sets of latent sign extension bugs at once!

File: header.c [hunk 2]
```diff
@@ -1642,6 +1642,7 @@ int sam_hdr_remove_except(sam_hdr_t *bh, const char *type, const char *ID_key, c
     return 0;
 }
 
+// cppcheck-suppress funcArgOrderDifferent
 int sam_hdr_remove_lines(sam_hdr_t *bh, const char *type, const char *id, void *h) {
```
Comment (jmarshall) [inline header.c]: Could be fixed instead by renaming the last parameter:

```suggestion
int sam_hdr_remove_lines(sam_hdr_t *bh, const char *type, const char *id, void *vrh) {
```

File: cram/cram_decode.c [hunk 3]
```diff
@@ -1145,9 +1145,10 @@ static int cram_decode_seq(cram_fd *fd, cram_container *c, cram_slice *s,
 
         if (ncigar+2 >= cigar_alloc) {
             cigar_alloc = cigar_alloc ? cigar_alloc*2 : 1024;
```
Comment (jmarshall) [inline cram/cram_decode.c]: This false alarm (and the same one in _htslib/kbitset.h_) no longer occurs with current development cppcheck 1.90pre.

File: cram/cram_encode.c [hunk 4]
```diff
@@ -48,6 +48,7 @@ OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #include "htslib/hts.h"
 #include "htslib/hts_endian.h"
 
+// cppcheck-suppress unknownMacro
```
Comment (jmarshall) [inline cram/cram_encode.c]: I think this is an artefact of not using `cppcheck -I.`

File: thread_pool.c [hunk 5]
```diff
@@ -60,7 +60,8 @@ static int worker_id(hts_tpool *p) {
 int DBG_OUT(FILE *fp, char *fmt, ...) {
     va_list args;
     va_start(args, fmt);
-    return vfprintf(fp, fmt, args);
+    int ret = vfprintf(fp, fmt, args);
```
Comment (jmarshall) [inline thread_pool.c]: The `#else` dummy `DBG_OUT` is `void`, so really just discard this return value and change the function declaration to `void DBG_OUT(etc)`.

**Comment by jmarshall** [comment]
IMHO it would be good to split this into the parts that fix actual defects (the lack of error handling in _hfile_s3.c_, the miscellaneous test code leaks and %d vs. %u stuff) and get that merged (with commit messages like _Fix order_query_string() error handling_ etc).

Then separately look at the best way to suppress the remaining cppcheck blather.

**Comment by daviesrob** [comment]
Rebased with a few extra fixes.  It's now in three commits:

1. Fixes for cppcheck-1.9 warnings that look like genuine problems in htslib.

2. Fixes for other warnings from cppcheck 1.9 that are either false positives; real problems in test harness code; or problems in code that is not usually built (e.g. code to print out debugging messages).  These two commits should result in a clean output from cppcheck 1.9.

3. Fixes for some of the remaining warnings printed by cppcheck 1.8, which is still the default for some current Linux distributions.  These are mostly `if` statements with the side-effect of allocating something, which can be easily fixed by doing the allocation then the `if`.  A couple of more complicated cases of this haven't been fixed as they would be rather more painful to do, and there probably isn't much point as cppcheck 1.9 gets them right anyway.

**Comment by jmarshall** [comment]
The recent cppcheck release is 1.90; the release with more false positives that's still in Debian & Ubuntu is 1.86. (1.08 and 1.09 were well over a decade ago!)

Your ‘genuine problems’ commit still contains a number of `realloc`-related changes that were previously cppcheck false positives and that are no longer produced by cppcheck 1.90. (Namely 3 x `cig_tmp` changes in _cram_decode.c_ and the _kbitset.h_ change.)

IMHO the original code is fine and also clearer. If you really want to suppress these false positives from an outdated version of an ad hoc linter, you could pessimise the code less by just changing the `realloc` argument instead: `if (cigar = realloc(s->cigar, …)` and `bs = (kbitset_t *) realloc(*bsp, …)`.

**Comment by daviesrob** [comment]
The `realloc` related stuff has been simplified and moved into the second commit.  I've also fixed the incorrect cppcheck version number in the commit messages.

The fixes for the old version have been removed.  It started complaining about pointers allocated by `hts_resize()`, so I've given up on it.
