### PR TITLE
Faidx bug fixes

### LINKED ISSUE #521: `faidx` can construct but not retrieve sequence names containing ligatures
I have been bestowed a FASTA that for reasons completely beyond me, contains several sequences featuring ligatures. I am able to construct a reference for this FASTA using `samtools faidx` as usual. One such record appears as such:

```
...
Ruminococcus_ﬂavefaciens_007C|name=Ruminococcus_flavefaciens_str=007c_contig00926_length=1993_numreads=700      1993    6895120 60      61
...
```

However, upon trying to retrieve this reference:

```
samtools faidx ref-seq.fa 'Ruminococcus_ﬂavefaciens_007C|name=Ruminococcus_flavefaciens_str=007c_contig00018_length=116710_numreads=23558'
[fai_build_core] ignoring duplicate sequence "Ruminococcus_" at byte offset 34320754
[fai_build_core] ignoring duplicate sequence "Ruminococcus_" at byte offset 35266281
[fai_build_core] ignoring duplicate sequence "Ruminococcus_" at byte offset 42873799
[fai_build_core] ignoring duplicate sequence "Ruminococcus_" at byte offset 44101083
[fai_build_core] ignoring duplicate sequence "Ruminococcus_" at byte offset 58253508
[fai_build_core] ignoring duplicate sequence "Ruminococcus_" at byte offset 69352525
[fai_build_core] ignoring duplicate sequence "Ruminococcus_" at byte offset 80055477
[fai_build_core] ignoring duplicate sequence "Ruminococcus_" at byte offset 97948810
[fai_build_core] ignoring duplicate sequence "Ruminococcus_" at byte offset 102928692
[fai_build_core] ignoring duplicate sequence "Ruminococcus_" at byte offset 114676623
[fai_build_core] ignoring duplicate sequence "Ruminococcus_" at byte offset 140255552
[fai_build_core] ignoring duplicate sequence "Ruminococcus_" at byte offset 177124649
[fai_build_core] ignoring duplicate sequence "Ruminococcus_" at byte offset 185400154
[fai_build_core] ignoring duplicate sequence "Ruminococcus_" at byte offset 202268453
[fai_build_core] ignoring duplicate sequence "Ruminococcus_" at byte offset 227675696
[fai_build_core] ignoring duplicate sequence "Ruminococcus_" at byte offset 235560450
[fai_build_core] ignoring duplicate sequence "Ruminococcus_" at byte offset 238127448
[fai_build_core] ignoring duplicate sequence "Ruminococcus_" at byte offset 243149824
[fai_build_core] ignoring duplicate sequence "Ruminococcus_" at byte offset 244996504
[fai_build_core] ignoring duplicate sequence "Ruminococcus_" at byte offset 245042023
[fai_build_core] ignoring duplicate sequence "Ruminococcus_" at byte offset 248144080
[fai_build_core] ignoring duplicate sequence "Ruminococcus_" at byte offset 265353073
[fai_build_core] ignoring duplicate sequence "Ruminococcus_" at byte offset 265779214
[fai_build_core] ignoring duplicate sequence "Ruminococcus_" at byte offset 269439913
[fai_build_core] ignoring duplicate sequence "Ruminococcus_" at byte offset 272340321
[fai_build_core] ignoring duplicate sequence "Ruminococcus_" at byte offset 272501745
[fai_build_core] ignoring duplicate sequence "Ruminococcus_" at byte offset 279500320
[fai_build_core] ignoring duplicate sequence "Ruminococcus_" at byte offset 295789512
[fai_build_core] ignoring duplicate sequence "Ruminococcus_" at byte offset 304298292
[fai_build_core] ignoring duplicate sequence "Ruminococcus_" at byte offset 323544190
[fai_build_core] ignoring duplicate sequence "Ruminococcus_" at byte offset 331997823
[fai_build_core] ignoring duplicate sequence "Ruminococcus_" at byte offset 348822550
[fai_build_core] ignoring duplicate sequence "Ruminococcus_" at byte offset 350312897
[fai_build_core] ignoring duplicate sequence "Ruminococcus_" at byte offset 353729289
[fai_build_core] ignoring duplicate sequence "Ruminococcus_" at byte offset 370481512
[fai_build_core] ignoring duplicate sequence "Ruminococcus_" at byte offset 376099242
[fai_build_core] ignoring duplicate sequence "Ruminococcus_" at byte offset 385724105
[fai_build_core] ignoring duplicate sequence "Ruminococcus_" at byte offset 402086549
>Ruminococcus_ﬂavefaciens_007C|name=Ruminococcus_flavefaciens_str=007c_contig00018_length=116710_numreads=23558
[fai_fetch] Warning - Reference Ruminococcus_ﬂavefaciens_007C|name=Ruminococcus_flavefaciens_str=007c_contig00018_length=116710_numreads=23558 not found in FASTA file, returning empty sequence
Failed to fetch sequence in Ruminococcus_ﬂavefaciens_007C|name=Ruminococcus_flavefaciens_str=007c_contig00018_length=116710_numreads=23558
```

It would appear a duplicate sequence error is returned for each of the ligature featuring sequences.
After some inspection, I believe I have traced the issue to [a call is `isgraph` as part of `fai_read`](https://github.com/samtools/htslib/blob/af89ccb237ce975b06413579efbc6eeabf3a9cc5/faidx.c#L215), which causes early truncation of sequence names.

I would propose a patch to simply alter `isgraph` to match the `fai_build_core`'s use of `!isspace`. But my previous interactions with pull requests leave me to anticipate that this may require further input first.

### LINKED ISSUE #522: `faidx` returns a 0-length sequence if a reference not in the index is suffixed with a colon
```
[sam@tatl faidx]$ cat seq.fa
>one
ACGT
>two
ACGT
[sam@tatl faidx]$ samtools faidx seq.fa
[sam@tatl faidx]$ samtools faidx seq.fa 'one'
>one
ACGT
[sam@tatl faidx]$ samtools faidx seq.fa 'one:'
>one:
ACGT
[sam@tatl faidx]$ samtools faidx seq.fa 'three'
>three
[fai_fetch] Warning - Reference three not found in FASTA file, returning empty sequence
Failed to fetch sequence in three
[sam@tatl faidx]$ samtools faidx seq.fa 'three:'
>three:
```

### PR DESCRIPTION
**Pull request by daviesrob**
Make `faidx_read()` use `isspace()` instead of `isgraph()` to find the end of the sequence name.  This fixes a problem uncovered when someone used a UTF-8 encoded ligature in a fasta file sequence name.  Searching for such a name requires the use of the exact binary representation in the original fasta file (we don't try anything clever like normalising UTF-8), but is at least now possible.  Fixes #521.

Improve fai_fetch() and faidx_fetch_seq().  Fixes #522 where a non-existent sequence name followed
by a colon would be incorrectly returned as an empty sequence.  This also fixes a few other problems with region parsing, adds more error checking and removes some code duplication.

### CODE REVIEW

File: faidx.c [hunk 1]
```diff
@@ -212,8 +213,10 @@ static faidx_t *fai_read(hFILE *fp, const char *fname)
     if (!buf) goto fail;
 
     while ((l = hgetln(buf, 0x10000, fp)) > 0) {
-        for (p = buf; *p && isgraph_c(*p); ++p);
-        *p = 0; ++p;
+        for (p = buf; *p && !isspace(*p); ++p);
```
Comment (mcshane) [inline faidx.c]: Should this be `isspace_c` from `hts_internal.h`?

Comment (daviesrob) [inline faidx.c]: I don't think it's necessary these days.  The annoying warnings that it's trying to suppress seem to have gone away these days - presumably thanks to a more sensible implementation of `isspace()` etc. in libc.

Comment (jmarshall) [inline faidx.c]: The commentary in _hts_internal.h_ is intended to explain why it's necessary, and the commit message that added the functions notes which particular platform still emits annoying messages.  (Surprisingly enough, it's Windows.)

Comment (daviesrob) [inline faidx.c]: Windows.... who could have guessed?
